os: osx
osx_image: xcode8
language: c

env:
  global:
    - HOMEBREW_NO_ANALYTICS=1
    - HOMEBREW_NO_AUTO_UPDATE=1
    - MACOS=1

before_install:
  - curl -fsSOL https://raw.githubusercontent.com/Homebrew/install/master/uninstall
  - sudo ruby uninstall --force
  - rm uninstall
  - hash -r

before_script:
  - echo | ruby -e "$(curl -fsSL https://raw.githubusercontent.com/autobrew/install/master/install)"
  - HOMEBREW_TAP_DIR="$(brew --repo "$TRAVIS_REPO_SLUG")"
  - mkdir -p "$HOMEBREW_TAP_DIR"
  - rm -rf "$HOMEBREW_TAP_DIR"
  - ln -s "$PWD" "$HOMEBREW_TAP_DIR"
  - brew help # trigger vendored ruby installation
#  - brew install v8 # just to test we are using autobrew bottles

script:
  - echo "Building commit range $TRAVIS_COMMIT_RANGE"  
  - brew test-bot --local --skip-setup --skip-homebrew
  - brew test-bot --ci-upload --dry-run
